import { Geist, Geist_Mono } from "next/font/google";
import { Poppins } from "next/font/google";
import "./globals.css";
import '../../public/css/style.css';
import '../../public/css/responsive.css';
import '../../public/css/developer.css';
import '../../public/css/customcss.css';

// import 'bootstrap/dist/js/bootstrap.bundle.min'; 


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins", // 👈 Define as a CSS variable
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <script src="https://kit.fontawesome.com/baf14c335c.js" crossOrigin="anonymous"></script> */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased`}
        // 👆 Loads all fonts but doesn't apply Poppins globally
      >
        {children}
      </body>
    </html>
  );
}